version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketprice_api
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: